### ISSUE TITLE
Sugarcube: place is not defined

### ISSUE THREAD

**Issue by mandrasch** [th0ma5w/Twine_Fullscreen_YouTube#1]
Hey! Thanks a lot for providing this macro! :)

Unfortunately it does not work with the sugarcube format, the error message is: "place is not defined"

Best Regards,
Matthias

**Comment by th0ma5w** [comment]
Hey there! Thanks for submitting an issue. I've added two new files to support Sugarcube. Look for the script file and style file with the "_sugarcube" in their name, and use their contents in place of the other stuff. I'll leave this issue open until you have a time to test it... let me know how it works for you!!

**Comment by mandrasch** [comment]
Hey! thanks very much for the quick reply and your effort! they are some syntax errors in your file (closing tags after Macro.add functions), but in general it worked for me. But there were some issues which i could not really reproduce and I think they were caused by the iframe API.

I now switched to self-hosted html5 video. But thank you very much for providing this macro set, which was a really good starting point for me! :)

**Comment by th0ma5w** [comment]
Okay, so I'll close this. Sorry it didn't fit into your project. Hopefully this will be of use to others. I'll try to clean up the code some. If you can comment on a closed issue, be sure to leave me a link to your project if you'd like, I'll definitely check it out! Otherwise ping me on Twitter or something. Best of luck!
